services:
  user:
    build:
      context: .
      dockerfile: ./apps/user/Dockerfile
      target: development
    command: npm run start:dev user
    env_file:
      - ./apps/user/.env
    ports:
      - '3000:3000'
    volumes:
      - .:/usr/src/app
  notification:
    build:
      context: .
      dockerfile: ./apps/notification/Dockerfile
      target: development
    command: npm run start:dev notification
    env_file:
      - ./apps/notification/.env
    volumes:
      - .:/usr/src/app
  mongo:
    image: mongo
  rabbitmq:
    image: rabbitmq
    ports:
      - 5672:5672
